export const csvConfig = {
  chartKeywords: ["Explanation", "Pace", "Interaction", "Practical", "Overall"],
  commentKeywords: [
    "Theory",
    "Lab",
    "Comments",
    "Remarks",
    "Feedback",
    "Suggestion",
  ],
  ignoreKeywords: ["Name", "ID", "PRN", "Email", "Roll", "Timestamp"],
  defaultFeedbackVocabulary: [
    "Good",
    "Very Good",
    "Excellent",
    "Average",
    "Poor",
    "Very Slow",
    "Slow",
    "Normal",
    "Fast",
    "Very Fast",
  ],
  commentNoiseFilters: [
    "na",
    "n/a",
    "none",
    "nil",
    "nothing",
    "no comment",
    "no comments",
    ".",
    "na.",
    "n.a.",
    "-",
    "--",
    "..",
  ],
};
