export const csvConfig = {
  chartKeywords: [
    "Explanation",
    "Pace",
    "Interaction",
    "Practical",
    "Overall",
    "Rating",
    "Score",
    "Quality",
  ],
  commentKeywords: [
    "Theory",
    "Lab",
    "Comments",
    "Remarks",
    "Feedback",
    "Suggestion",
    "Review",
  ],
  ignoreKeywords: ["Name", "ID", "PRN", "Email", "Roll", "Timestamp"],
  defaultFeedbackVocabulary: [
    "Good",
    "Very Good",
    "Excellent",
    "Average",
    "Poor",
    "Very Slow",
    "Slow",
    "Normal",
    "Fast",
    "Very Fast",
  ],
  commentNoiseFilters: [
    "na",
    "n/a",
    "none",
    "nil",
    "nothing",
    "no comment",
    "no comments",
    "No",
    "None",
    "Null",
    ".",
    "na.",
    "n.a.",
    "-",
    "--",
    "..",
  ],
};
